spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${USER_ID}
            client-secret: ${USER_SECRET}
            scope: profile, email
  datasource:
    url: jdbc:mysql://localhost:3306/social_network
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 3000000
      refresh-token:
        expiration: 6000000
main:
  servlet:
    multipart:
      max-file-size: 52428800
      max-request-size: 52428800
  codec:
    max-in-memory-size: 52428800
server:
  tomcat:
    max-swallow-size: 52428800
aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID}
  secret:
    key: ${AWS_SECRET_ACCESS_KEY}
  region: sa-east-1
  s3:
    bucket:
      name: twitter-clon-app
